### ISSUE TITLE
Suggestion for configuration: option to clear funds on death

### ISSUE THREAD

**Issue by BrianV1981** [gruppe-adler/grad-moneyMenu#4]
After I respawn I still have my funds and I can also run back and get the funds that I had before dying.

**Comment by BrianV1981** [comment]
You can also add the exact opposite option. When you die, the money will not be on the corpse, but will remain on the character after respawning.

**Comment by McDiod** [comment]
> clear funds on death

This should be the default behaviour, so I'm guessing you found a bug. I'll try to reproduce.

**Comment by McDiod** [comment]
Added in [0.3.0](https://github.com/gruppe-adler/grad-moneyMenu/releases/tag/0.3.0).
