### ISSUE TITLE
Changing money variable

### ISSUE THREAD

**Issue by RaidenKoizuma** [gruppe-adler/grad-moneyMenu#5]
So I use https://github.com/HallyG/HALs_Store as a shop system which stores a unit's money as HALs_money_funds. Is there support for changing the variable the script uses to another shop systems?

**Comment by McDiod** [comment]
There isn't. Find all and replace is your best bet I guess.

**Comment by RaidenKoizuma** [comment]
So Update: it actually bloody works! I find/replace every "grad_lbm_myFunds" with "HALs_money_funds". So I can now use moneymenu and your shop addon to have a vehicle shop, bank account, and money transferring, which are the only features missing from HALs. I have no idea how or why but it works.
